name: "Test Action"

on:
  push:
    branches: dev
    
defaults:
  run:
    shell: bash
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "CREATE_PR=true" >> $GITHUB_ENV
          echo "CREATE_PR="$CREATE_PR
      - name: Final step
        if: ${{ env.CREATE_PR == true }}
        run: echo "Run final step"
