name: "Test Action"

on:
  push:
    branches: dev
    
defaults:
  run:
    shell: bash
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CREATE_PR=false" >> $GITHUB_ENV
      - name: Final step
        if: env.CREATE_PR == true
        run: echo "Creating the PR"
