name: "Test Action"

on:
  push:
    branches: dev
    
defaults:
  run:
    shell: bash
    
jobs:
  test-job:
    env:
      CREATE_PR: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: ${{ env.CREATE_PR='true' }}
      - name: Final step
        if: ${{ env.CREATE_PR == 'true' }}
        run: echo "Creating the PR"
