name: "Test Action"

on:
  push:
    branches: dev
    
defaults:
  run:
    shell: bash
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-env name=CREATE_PR::true"
      - name: Final step
        if: env.CREATE_PR
        run: echo "Creating the PR"
