name: "Test Action"

on:
  push:
    branches: dev
    
defaults:
  run:
    shell: bash
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "CREATE_PR=false" >> $GITHUB_ENV
          echo "CREATE_PR="${{ env.CREATE_PR }}
          
      - name: Final step
        run: if ${{ env.CREATE_PR }}; then echo "Run final step"; fi
